2. Erronka/WineShop/WineShop/Models/Ardoa.cs
namespace WineShop.Models
{
    public class Ardoa
    {
        public int Id { get; set; }
        public string Izena { get; set; }
        public Decimal Salneurria { get; set; }
        public int Alkohola { get; set; }
        public int Edukia { get; set; }
        public int Urtea { get; set; }
        public string Irudia { get; set; }
        public string Deskribapena { get; set; }
        public bool Eskaintza { get; set; }
        public int Deskontua { get; set; }
        public int UpeltegiaId { get; set; }
        public int MotaId { get; set; }
        public virtual Mota Mota { get; set; }
    }
}

2. Erronka/WineShop/WineShop/Models/ArdoaUpeltegi.cs
namespace WineShop.Models
{
    public class ArdoaUpeltegi
    {
        public int Id { get; set; }
        public string Izena { get; set; }
        public string UpeltegiIzena { get; set; }
    }


}

2. Erronka/WineShop/WineShop/Models/ErrorViewModel.cs
namespace WineShop.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

2. Erronka/WineShop/WineShop/Models/Mota.cs
using System.ComponentModel.DataAnnotations;

namespace WineShop.Models
{
    public class Mota
    {
        [Key]
        public int Id { get; set; }
        public string Izena { get; set; }
        public virtual IList<Ardoa> Ardoak { get; set; }

    }
}

2. Erronka/WineShop/WineShop/Models/SaskiaAlea.cs
using System.ComponentModel.DataAnnotations;

namespace WineShop.Models
{
    public class SaskiaAlea
    {
        [Key]
        public int Id { get; set; }
        public string SaskiaId { get; set; }
        public int Kantitatea { get; set; }
        public System.DateTime Data { get; set; }
        public int ArdoaId { get; set; }
    }
}

2. Erronka/WineShop/WineShop/ViewModels/SaskiaAleaViewModelbi.cs
namespace WineShop.ViewModels
{
    public class SaskiaAleaViewModelbi
    {
        public int ArdoaId { get; set; }
        public string Izena { get; set; }
        public string Irudia { get; set; }
        public int Kantitatea { get; set; }
        public decimal Salneurria { get; set; }
    }
}

2. Erronka/WineShop/WineShop/ViewModels/SaskiaViewModel.cs
using WineShop.ViewModels;

namespace Wineshop.ViewModels
{
    public class SaskiaViewModel
    {
        public IList<SaskiaAleaViewModelbi> SaskiaAleaVMList { get; set; }
    }
}

2. Erronka/WineShop/WineShop/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WineShop.Models;
using WineShop.Services;

namespace WineShop.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IArdoaService _ardoaService;

        public HomeController(ILogger<HomeController> logger, IArdoaService ardoaService)
        {
            _logger = logger;
            _ardoaService = ardoaService;
        }



        public async Task<IActionResult> Index()
        {
            List<Ardoa> ardoaList = new List<Ardoa>();
            ardoaList = await _ardoaService.GetArdoak();
            return View(ardoaList.Where(a => a.Eskaintza == true));
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

2. Erronka/WineShop/WineShop/Controllers/SaskiaController.cs
using Microsoft.AspNetCore.Mvc;
using Wineshop.ViewModels;
using WineShop.Models;
using WineShop.Services;
using WineShop.ViewModels;

namespace WineShop.Controllers
{
    public class SaskiaController : Controller
    {
        private readonly ISaskiaService _saskiaService;
        private readonly IArdoaService _ardoaService;
        public SaskiaController(ISaskiaService saskiaService, IArdoaService ardoaService)
        {
            _saskiaService = saskiaService;
            _ardoaService = ardoaService;
        }
        public async Task<IActionResult> Index(string id)
        {
            IList<SaskiaAlea> saskiaAleaList = new List<SaskiaAlea>();
            saskiaAleaList = await _saskiaService.SaskiaLortuAleak(id);
            //Ardo bakoitzaren datuak hartu eta ViewModel bezala sortu
            IList<SaskiaAleaViewModelbi> saskiaAleaVMList = new List<SaskiaAleaViewModelbi>();
            foreach (var saskiaAlea in saskiaAleaList)
            {
                var ardoa = await _ardoaService.GetArdoa(saskiaAlea.ArdoaId);
                SaskiaAleaViewModelbi saskiaAleaViewModel = new SaskiaAleaViewModelbi()
                {
                    ArdoaId = ardoa.Id,
                    Irudia = ardoa.Irudia,
                    Izena = ardoa.Izena,
                    Kantitatea = saskiaAlea.Kantitatea,
                    Salneurria = ardoa.Salneurria
                };
                saskiaAleaVMList.Add(saskiaAleaViewModel);
            }
            var saskiaViewModel = new SaskiaViewModel();
            saskiaViewModel.SaskiaAleaVMList = saskiaAleaVMList;
            return View(saskiaViewModel);
        }
    }
}

2. Erronka/WineShop/WineShop/ViewComponents/ArdoakViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WineShop.Services;

namespace WineShop.ViewComponents
{
    public class ArdoakViewComponent : ViewComponent
    {
        private readonly IArdoaService _ardoaService;
        public ArdoakViewComponent(IArdoaService ardoaService)
        {
            _ardoaService = ardoaService;
        }
        public async Task<IViewComponentResult> InvokeAsync(int id)
        {
            return View(await _ardoaService.GetMota(id));
        }

    }
}

2. Erronka/WineShop/WineShop/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<nav class="navbar navbar-expand-lg navbar-light bg-light bg-menua">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse erlatiboa" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown full-width">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Zuria
                    </a>
                    @await Component.InvokeAsync("Ardoak", new { id = 1 })
                    
                </li>
            </ul>
        </div>
    </div>
</nav>
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" arialabel="
Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="~/images/banner1.jpg" alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="~/images/banner2.jpg" alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="~/images/banner3.jpg" alt="Third slide">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
<div class="carousel-inner">
@{var itemLerroko = 0;
var fila1 = false;}

@{
foreach (var item in Model)
{
if (itemLerroko == 0)
{
if (fila1 == false)
{
@:<div class="carousel-item active">
@: <div class="row">
}
else
{
@:<div class="carousel-item">
@: <div class="row">
}
}


<div class="col-sm-3">
<div class="col-item">
<div class="photo text-center">
<img class="irudia" src="~/images/ardoak/@item.Irudia" alt="a" />
</div>
<div class="info">
<div class="row">
<div class="price col-md-6">
<h5>
@item.Deskribapena
</h5>

<span class="tachado">@item.Salneurria</span>
%@item.Deskontua
@{ decimal eskaintza = item.Salneurria - (item.Salneurria * item.Deskontua) / 100;}
<h5 class="price-text-color">
@eskaintza
</h5>
</div>
<div class="rating d-sm-none d-md-block col-md-6">
<i class="price-text-color fa fa-star"></i><i class="price-text-color fa fa-star">
</i><i class="price-text-color fa fa-star"></i><i class="price-text-color fa fa-star">
</i><i class="fa fa-star"></i>
</div>
</div>
<div class="separator clear-left">
<p class="btn-details">
<i class="fa fa-list"></i><a href="http://www.jquery2dotnet.com" class="d-sm-none d-md-block">Detaile gehiago</a>
</p>
<p class="btn-add">
<i class="fa fa-shopping-cart"></i>
<!-- esto es lo que nos dice lo que vamos a hacer. nos dice que habrimos el controller Saskia y el metodo SaskiaGehitu -->
<a asp-controller="Saskia" asp-action="SaskiaGehitu" asp-route-id="@item.Id">Karritora gehitu</a>
</p>
</div>
<div class="clearfix">
</div>
</div>
</div>
</div>

itemLerroko++;
fila1 = true;
if (itemLerroko > 3)
{
@:</div>
@:</div>
itemLerroko = 0;
}

}
}

</div>
</div>
</div>

2. Erronka/WineShop/WineShop/Views/Saskia/Index.cshtml
@using System.Globalization;
@model WineShop.ViewModels.SaskiaAleaViewModelbi
@{
    ViewData["Title"] = "Index";
}
<div class="container">
    <div id="update-message"></div>
    <table class="table table-striped">
        <thead>
            <tr class="borgona">
                <th>Izena</th>
                <th>Irudia</th>
                <th>Kantitatea</th>
                <th>Salneurria</th>
                <th>Guztira</th>
            </tr>
        </thead>
        @{
            decimal saskiaguztira = 0;
        }
        @foreach (var item in Model.SaskiaAleaVMList)
        {
            <tr id="row-@item.ArdoaId">
                <td>
                    @item.Izena
                </td>
                <td>
                    <img class="img-thumbnail altuera" id="thumbnail" src="~/images/ardoak/@item.Irudia" />
                </td>
                <td>
                    @item.Kantitatea
                </td>
                <td>
                    @item.Salneurria
                </td>
                <td>
                    @{
                        decimal guztira = item.Salneurria * item.Kantitatea;
                        saskiaguztira += guztira;
                    }
                    @guztira
                </td>
            </tr>
        }
        <tr>
            <td>
                <a class="btn btn-borgona text-light" asp-controller="Home" asp-action="Index">Bueltatu</a>
                <a class="btn btn-borgona text-light" asp-controller="Ordaindu" asp-action="Index">Ordaindu</a>
            </td>
            <td></td>
            <td></td>
            <td class="float-right"><p>Guztira: <span id="cart-total">@saskiaguztira.ToString("C2", CultureInfo.CurrentCulture)</span></p></td>
        </tr>
    </table>
</div>

2. Erronka/WineShop/WineShop/Views/Shared/Components/Ardoak/Default.cshtml
@model IEnumerable<WineShop.Models.ArdoaUpeltegi>
@if (Model != null) // poner este if else, es buena practica para que nos diga que n hay datos.
{
    <ul class="dropdown-menu">
        <li>
            <div class="container padinaMenu">
                <div class="col-md-4 nireMenua">
                    <h4 class="borgona">Aukeratu upeltegia:</h4>
                    @{
                        var izena = "";
                        foreach (var item in Model)
                        {
                            if (item.UpeltegiIzena != izena)
                            {
                                <a href="#">@Html.DisplayFor(modelItem => item.UpeltegiIzena)</a>

                                <br />
                                izena = item.UpeltegiIzena;
                            }
                        }
                    }
                </div>
                <div class="col-md-4">
                    <img class="img-responsive" src="~/images/wine-white.jpg" />
                </div>
            </div>
        </li>
    </ul>
}

else
{
    <li>No hay dats disponibles</li>
}

2. Erronka/WineShop/WineShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WineShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WineShop.styles.css" asp-append-version="true" />
    <!-- METEMOS ESTO DE LOS APUNTES -->
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WineShop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div>
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <img src="~/images/ardoa.jpg" />
                </div>
                <div class="col-md-6">
                    <form class="form-inline my-2 my-lg-0 float-right" id="searchForm">
                        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-danger my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
                    </form>
                </div>
            </div>
        </div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WineShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>